# Generated by Django 5.0.2 on 2026-07-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrective_actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='due_reminder_sent',
            field=models.BooleanField(default=False, help_text='True if 3-day due-soon reminder was sent'),
        ),
    ]
