# Generated by Django 5.0.2 on 2026-08-21 07:37

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrective_actions', '0002_correctiveaction_due_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionresponse',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='capa_evidence/%Y/%m/', validators=[apps.common.validators.UploadValidator()]),
        ),
    ]
