# Generated by Django 6.0.5 on 2026-09-29 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrective_actions', '0003_alter_actionresponse_evidence_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='correctiveaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Auditor who accepted the remediation plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actionresponse',
            name='status_update',
            field=models.CharField(choices=[('pending_approval', 'Pending Auditor Approval'), ('open', 'Open'), ('in_progress', 'In Progress'), ('partially_resolved', 'Partially Resolved'), ('evidence_submitted', 'Evidence Submitted / Pending Verification'), ('resolved', 'Resolved'), ('overdue', 'Overdue'), ('not_implemented', 'Not Implemented'), ('closed', 'Closed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Auditor Approval'), ('open', 'Open'), ('in_progress', 'In Progress'), ('partially_resolved', 'Partially Resolved'), ('evidence_submitted', 'Evidence Submitted / Pending Verification'), ('resolved', 'Resolved'), ('overdue', 'Overdue'), ('not_implemented', 'Not Implemented'), ('closed', 'Closed')], default='open', max_length=30),
        ),
    ]
