# Generated by Django 6.0.5 on 2026-05-26 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('objectives', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_programs', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='audit_planning.auditengagement')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_programs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('procedure_type', models.CharField(choices=[('test_of_controls', 'Test of Controls'), ('substantive', 'Substantive Testing'), ('analytical', 'Analytical Procedures'), ('inquiry', 'Inquiry'), ('observation', 'Observation'), ('inspection', 'Inspection & Re-performance')], default='substantive', max_length=30)),
                ('risk_area', models.CharField(blank=True, max_length=200)),
                ('assertion', models.CharField(blank=True, max_length=200)),
                ('expected_evidence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_procedures', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_procedures', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='audit_execution.auditprogram')),
            ],
            options={
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkingPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('paper_type', models.CharField(choices=[('planning', 'Planning Document'), ('program', 'Audit Program'), ('evidence', 'Evidence'), ('workpaper', 'Work Paper'), ('correspondence', 'Correspondence'), ('report', 'Report'), ('other', 'Other')], default='workpaper', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='working_papers/%Y/%m/')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_papers', to='audit_planning.auditengagement')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_papers', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_papers', to='audit_execution.auditprocedure')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reference'],
            },
        ),
    ]
