# Generated by Django 6.0.5 on 2026-09-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_execution', '0002_alter_workingpaper_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditprocedure',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed / Non-Compliant'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20),
        ),
    ]
