# Generated by Django 5.0.2 on 2026-08-15 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_directorate_type_department_staff_count'),
        ('audit_planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditengagement',
            name='directorate',
            field=models.ForeignKey(blank=True, help_text='EEU Internal Audit directorate that owns this engagement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directorate_engagements', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='auditengagement',
            name='technical_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Utility-specific technical audit parameters (Asset Type, Voltage Level, Feeder ID, Energy Loss Score, Engineering Compliance Rating, etc.).'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='directorate',
            field=models.ForeignKey(blank=True, help_text='Directorate that owns this plan segment. Null for the EEU Consolidated Master Plan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directorate_audit_plans', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, help_text='For directorate plans, the consolidated master plan they roll up into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_plans', to='audit_planning.auditplan'),
        ),
        migrations.AddField(
            model_name='auditplan',
            name='plan_scope',
            field=models.CharField(choices=[('directorate', 'Directorate Plan'), ('consolidated', 'EEU Consolidated Master Plan')], default='directorate', help_text='Whether this is a directorate-level plan or the consolidated master plan.', max_length=20),
        ),
        migrations.AddField(
            model_name='audituniverse',
            name='directorate',
            field=models.ForeignKey(blank=True, help_text='EEU Internal Audit directorate that owns this universe item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directorate_universe_items', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='audituniverse',
            name='technical_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Utility-specific technical audit parameters (Asset Type, Voltage Level, Feeder ID, Energy Loss Score, etc.).'),
        ),
        migrations.AlterField(
            model_name='auditengagement',
            name='engagement_type',
            field=models.CharField(choices=[('financial', 'Financial Audit'), ('performance', 'Performance Audit'), ('technical', 'Technical & Engineering Audit (Substations, Distribution Grids, Loss Reduction, Transmission)'), ('it', 'Information Technology Audit (ERP, CIS Billing, Cybersecurity, Infrastructure)'), ('special', 'Planning & Special Review Audit')], default='financial', max_length=50),
        ),
    ]
