# Generated by Django 6.0.5 on 2026-09-03 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_audittrail_action'),
        ('audit_planning', '0002_auditengagement_directorate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='EEU Projects Portfolio Management node (or owning unit) for this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
            ],
            options={
                'verbose_name': 'PPM Project',
                'verbose_name_plural': 'PPM Projects',
                'ordering': ['name'],
            },
        ),
    ]
