# Generated by Django 5.0.2 on 2026-09-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_region_user_service_center'),
        ('audit_planning', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditengagement',
            name='region',
            field=models.ForeignKey(blank=True, help_text='EEU region being audited, independent of department.', limit_choices_to={'unit_type': 'REGION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='auditengagement',
            name='service_center',
            field=models.ForeignKey(blank=True, help_text='Customer service center being audited, if any.', limit_choices_to={'unit_type': 'SERVICE_CENTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='audituniverse',
            name='region',
            field=models.ForeignKey(blank=True, help_text='EEU region this entity sits in, independent of department.', limit_choices_to={'unit_type': 'REGION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='audituniverse',
            name='service_center',
            field=models.ForeignKey(blank=True, help_text='Customer service center this entity sits in, if any.', limit_choices_to={'unit_type': 'SERVICE_CENTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.ForeignKey(blank=True, help_text='EEU region this project is delivered in, independent of department.', limit_choices_to={'unit_type': 'REGION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='project',
            name='service_center',
            field=models.ForeignKey(blank=True, help_text='Customer service center this project is delivered at, if any.', limit_choices_to={'unit_type': 'SERVICE_CENTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department'),
        ),
    ]
