# Generated by Django 6.0.5 on 2026-09-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0004_auditengagement_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditengagement',
            name='objectives',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='auditengagement',
            name='scope',
            field=models.TextField(),
        ),
    ]
