# Generated by Django 6.0.5 on 2026-09-30 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0005_alter_auditengagement_objectives_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditengagement',
            name='auditee',
            field=models.ForeignKey(blank=True, help_text='Department representative who answers for findings on this engagement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_engagements', to=settings.AUTH_USER_MODEL),
        ),
    ]
