# Generated by Django 6.0.5 on 2026-05-26 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_execution', '0001_initial'),
        ('audit_planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('informational', 'Informational')], max_length=20)),
                ('category', models.CharField(choices=[('control_deficiency', 'Control Deficiency'), ('compliance', 'Compliance Issue'), ('fraud', 'Fraud Risk'), ('operational', 'Operational Weakness'), ('financial', 'Financial Misstatement'), ('it_security', 'IT/Security Issue'), ('governance', 'Governance Issue'), ('other', 'Other')], default='control_deficiency', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('disputed', 'Disputed')], default='open', max_length=20)),
                ('condition', models.TextField(blank=True, help_text='What did we find?')),
                ('criteria', models.TextField(blank=True, help_text='What should exist (policy/standard)?')),
                ('cause', models.TextField(blank=True, help_text='Why did it happen (root cause)?')),
                ('effect', models.TextField(blank=True, help_text='What is the impact/risk?')),
                ('recommendation', models.TextField(blank=True)),
                ('management_response', models.TextField(blank=True)),
                ('risk_impact', models.TextField(blank=True)),
                ('root_cause_category', models.CharField(blank=True, max_length=100)),
                ('target_resolution_date', models.DateField(blank=True, null=True)),
                ('actual_resolution_date', models.DateField(blank=True, null=True)),
                ('is_repeat', models.BooleanField(default=False, help_text='Is this a repeat finding?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_findings', to=settings.AUTH_USER_MODEL)),
                ('auditee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditee_findings', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit_planning.auditengagement')),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_findings', to=settings.AUTH_USER_MODEL)),
                ('previous_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='findings.auditfinding')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='audit_execution.auditprocedure')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('screenshot', 'Screenshot'), ('spreadsheet', 'Spreadsheet'), ('photo', 'Photo'), ('video', 'Video'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='findings.auditfinding')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FindingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='findings.auditfinding')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
