# Generated by Django 5.0.2 on 2026-08-21 07:37

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(upload_to='evidence/%Y/%m/', validators=[apps.common.validators.UploadValidator()]),
        ),
    ]
