# Generated by Django 6.0.5 on 2026-09-29 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_execution', '0003_alter_auditprocedure_status'),
        ('findings', '0002_alter_evidence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfinding',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='audit_execution.auditprocedure'),
        ),
    ]
