# Generated by Django 6.0.5 on 2026-09-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0003_alter_auditfinding_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfinding',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('awaiting_auditee_response', 'Awaiting Auditee Response'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('disputed', 'Disputed')], default='open', max_length=30),
        ),
    ]
