# Generated by Django 6.0.5 on 2026-09-30 08:00

from django.db import migrations, models


def publish_existing_findings(apps, schema_editor):
    """Move findings raised before publication was a gate into a visible state.

    Until now `open` was what the API created and the auditee scope had no status
    filter, so every one of these rows has been visible to its auditee all along.
    `open` is a pre-publication state now, so leaving them there would blank the
    findings list and the My Work queue of every auditee in the system. Publishing
    them preserves what those users can already see.

    The split matters: a row carrying a `management_response` has already been
    answered, so the ball is with the audit team and publishing it back to
    `awaiting_auditee_response` would ask the auditee a second time.
    """
    AuditFinding = apps.get_model('findings', 'AuditFinding')
    AuditFinding.objects.filter(status='open').exclude(
        management_response='',
    ).update(status='in_progress')
    # Whatever is left was never answered, so it goes out to the auditee.
    AuditFinding.objects.filter(status='open').update(
        status='awaiting_auditee_response',
    )


def unpublish_findings(apps, schema_editor):
    """Best-effort reverse, and deliberately partial.

    This restores the rows that were simply awaiting a first response. It cannot
    restore the `open` rows that were already answered before the migration,
    because nothing distinguishes them from a finding the auditee answered after
    being published — both are `in_progress` with a response. Those are left
    alone, which is the safe direction: rolling back leaves them visible, and
    re-applying the migration is a no-op for them.
    """
    AuditFinding = apps.get_model('findings', 'AuditFinding')
    AuditFinding.objects.filter(
        status='awaiting_auditee_response', management_response='',
    ).update(status='open')


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0004_alter_auditfinding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfinding',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('awaiting_auditee_response', 'Awaiting Auditee Response'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('disputed', 'Disputed')], default='draft', max_length=30),
        ),
        migrations.RunPython(publish_existing_findings, unpublish_findings),
    ]
