# Generated by Django 6.0.5 on 2026-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findings', '0005_alter_auditfinding_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfinding',
            name='status',
            field=models.CharField(choices=[('draft', 'Pending Supervisor Review'), ('open', 'Open'), ('awaiting_auditee_response', 'Awaiting Auditee Response'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('disputed', 'Disputed')], default='draft', max_length=30),
        ),
    ]
