# Generated by Django 6.0.5 on 2026-07-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(default='TEMP-00000', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
