# Generated by Django 5.0.2 on 2026-08-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_change_username_field_to_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='directorate_type',
            field=models.CharField(choices=[('IAEO', 'Internal Audit Executive Office'), ('FPA', 'Financial & Performance Audit Directorate'), ('TA', 'Technical Audit Directorate'), ('ITA', 'Information Technology Audit Directorate'), ('PP', 'Planning & Performance Directorate'), ('OTHER', 'Other / Non-Directorate')], default='OTHER', help_text='Explicit EEU Internal Audit directorate classification.', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='staff_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of staff assigned to this directorate.'),
        ),
    ]
