# Generated by Django 6.0.5 on 2026-08-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_department_directorate_type_department_staff_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_title',
            field=models.CharField(blank=True, help_text='Title of the officer leading this unit, e.g. "Chief Finance officer".', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='head_title_am',
            field=models.CharField(blank=True, help_text='Amharic officer title.', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='name_am',
            field=models.CharField(blank=True, help_text='Amharic name, shown when the interface language is Amharic.', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='unit_type',
            field=models.CharField(choices=[('EXECUTIVE', 'Executive Office'), ('CORPORATE', 'Corporate Department / Chief Office'), ('AUDIT', 'Internal Audit Directorate'), ('REGION', 'Region')], default='CORPORATE', help_text='Where this unit sits in the EEU organizational structure.', max_length=20),
        ),
    ]
