# Generated by Django 6.0.5 on 2026-08-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_department_head_title_department_head_title_am_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='unit_type',
            field=models.CharField(choices=[('EXECUTIVE', 'Executive Office'), ('CORPORATE', 'Corporate Department / Chief Office'), ('AUDIT', 'Internal Audit Directorate'), ('REGION', 'Region'), ('SERVICE_CENTER', 'Customer Service Center')], default='CORPORATE', help_text='Where this unit sits in the EEU organizational structure. The corporate side nests three deep: chief office -> region -> customer service center.', max_length=20),
        ),
    ]
