# Generated by Django 5.0.2 on 2026-08-21 07:37

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_department_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.common.validators.UploadValidator(('png', 'jpg', 'jpeg', 'gif', 'webp'), 2097152)]),
        ),
    ]
