# Generated by Django 5.0.2 on 2026-09-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_backfill_legacy_department_amharic_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, help_text='EEU region this user is based in, independent of their department.', limit_choices_to={'unit_type': 'REGION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='service_center',
            field=models.ForeignKey(blank=True, help_text='Customer service center this user is posted to.', limit_choices_to={'unit_type': 'SERVICE_CENTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department'),
        ),
    ]
