# Generated by Django 6.0.5 on 2026-10-05 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_region_user_service_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='region',
            field=models.ForeignKey(blank=True, help_text='For a regional audit unit (e.g. FPA-RGN-BA), the EEU REGION department it audits. Drives RegionScopeMixin — users in this unit see only records tagged with this region. Leave blank for HQ units.', limit_choices_to={'unit_type': 'REGION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department'),
        ),
    ]
