# Generated by Django 6.0.5 on 2026-05-26 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('engagement', 'Engagement Report'), ('findings', 'Findings Summary'), ('management', 'Management Report'), ('board', 'Board Report'), ('followup', 'Follow-up Report'), ('risk', 'Risk Assessment Report'), ('kpi', 'KPI Dashboard Report')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='report_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('word', 'Word')], max_length=10)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='generated_reports/%Y/%m/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='audit_planning.auditengagement')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reporttemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
