# Generated by Django 5.0.2 on 2026-08-21 07:37

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='report_templates/', validators=[apps.common.validators.UploadValidator()]),
        ),
    ]
