# Generated by Django 5.0.2 on 2026-08-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_planning', '0001_initial'),
        ('risk_assessment', '0002_selfassessment_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='audit_universe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='audit_planning.audituniverse'),
        ),
    ]
