# Generated by Django 5.0.2 on 2026-09-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_region_user_service_center'),
        ('risk_assessment', '0003_riskassessment_audit_universe'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='region',
            field=models.ForeignKey(blank=True, help_text='EEU region being assessed, independent of department.', limit_choices_to={'unit_type': 'REGION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='service_center',
            field=models.ForeignKey(blank=True, help_text='Customer service center being assessed, if any.', limit_choices_to={'unit_type': 'SERVICE_CENTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.department'),
        ),
    ]
