# Generated by Django 6.0.5 on 2026-09-29 13:06

from django.db import migrations, models


def approve_pre_existing(apps, schema_editor):
    """Treat rows that predate the approval workflow as already approved.

    The field defaults to `draft`, which is right for anything scored from now on
    — an assessor should not be able to make a score official by pressing save.
    Applied to *existing* rows, though, it would retroactively demote assessments
    that were live under the old rules and whose scores are already sitting on
    their auditable entities. Those rows have nobody to name as reviewer (there
    was no review step), so the honest backfill is to leave them as they were
    found: in force. New rows are unaffected and start as drafts.
    """
    RiskAssessment = apps.get_model('risk_assessment', 'RiskAssessment')
    RiskAssessment.objects.update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0007_alter_riskassessment_control_effectiveness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.RunPython(approve_pre_existing, migrations.RunPython.noop),
    ]
